# Generated by Django 3.1.7 on 2021-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210413_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentqueue',
            name='inQueue',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentqueue',
            name='sessionBeginTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studentqueue',
            name='sessionEndTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='studentqueue',
            name='timeLeft',
            field=models.DateTimeField(null=True),
        ),
    ]
