# Generated by Django 3.1.7 on 2021-04-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210413_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True, null=True)),
                ('student_id', models.IntegerField()),
                ('studentName', models.CharField(max_length=250)),
                ('TutorName', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('report', models.TextField(max_length=3000)),
            ],
        ),
    ]
