# Generated by Django 3.1.7 on 2021-04-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210422_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeoffrequest',
            name='approved',
            field=models.CharField(default='Pending', max_length=250),
        ),
    ]
