# Generated by Django 3.1.7 on 2021-04-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_timeoffrequest_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqueue',
            name='student_id',
            field=models.SlugField(max_length=40),
        ),
    ]
