# Generated by Django 3.1.7 on 2021-04-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210423_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentqueue',
            name='student_id',
            field=models.IntegerField(),
        ),
    ]
