# Generated by Django 3.1.7 on 2021-04-27 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210423_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentqueue',
            name='tutorname',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
