# Generated by Django 3.1.7 on 2021-05-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorinator', '0002_auto_20210504_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastName',
        ),
    ]
