# Generated by Django 3.1.7 on 2021-05-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutorinator', '0005_timeoffrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='change',
            field=models.CharField(default='No Change', max_length=3000),
        ),
        migrations.AddField(
            model_name='schedule',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule',
            field=models.CharField(default='No Schedule', max_length=3000),
        ),
    ]
